/* Nex.js 전역설정 담당 파일 // 바닐라 리액트 - App.jsx ( 최상단 로직(초기화 로직) ) + Layout.jst ( 공통UI(헤더 / 푸터) ) - 전체 뼈대 */

'use client'; // 클라이언트 컴포넌트로 지정
/*
Next.js App Router는 기본이 서버 컴포넌트. 
'use client'; 클라이언트 컴포넌트로 선언 - useEffect나 useState, Zustand 사용을 위함
*/

import QueryProvider from '@/providers/QueryProvider';
import AuthProvider from '../providers/AuthProvider';
import Header from '@/components//layout/common/Header';
import { useAuthStore } from '@/stores/authStore';
import GlobalModal from '@/components/common/modal/GlobalModal';
//import { useProfileQuery } from '../hooks/login/useAuthMutation';
// ?? 임시주석 ... 안쓰는거같은데? import { useProfileQuery } from '../hooks/login/useAuth';


import "./globals.css"; // 기존 index.css 등
//import Link from 'next/link';
//import { useRouter } from 'next/navigation';
//import { useEffect } from 'react';
//import { useRouter, usePathname } from 'next/navigation'; // Next.js용 라우터
//import { useLogoutMutation, useProfileQuery } from '@/hooks/login/useAuthMutation'; // 훅 임포트
/*
  usePathname을 통해 현재 위치가 로그인 페이지인지 확인하여 UI를 더 세밀하게 조정
*/


export default function RootLayout({ children }: { children: React.ReactNode }) {

  const { isInitialized } = useAuthStore();
  
  /** TanStack Query */
  // 프로필 조회 쿼리 실행 (새로고침 시 자동 실행)
  // isLoading은 데이터가 올 때까지 true
  //////////const { isLoading: isProfileLoading } = useProfileQuery();
  // 2. 로그아웃 Mutation 실행 함수
  //const { mutate: logoutMutate } = useLogoutMutation();

  /**
   * 초기화 체크 (isInitialized)
   * 서버로부터 유저 정보를 받아오기 전까지(최초 1회) 로딩 화면 노출
   * [보안/깜빡임](로그인 안 된 것처럼 보이다가 갑자기 로그인 됨)을 방지
   */
  // 초기화 중일 때 (서버 응답 기다리는 중)
/**********  
  if(!isInitialized && isProfileLoading) {
    return (
      <html lang="ko">
        <body>
          <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
            <span>인증 확인 중...</span>
          </div>
        </body>
      </html>
    )

  }
*/

  // Brand Color ( #488ad8 )
  // Round ( 2x1 / 3x1 )

  // 레이아웃 렌더링
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <AuthProvider>
            {/* 분리된 헤더 컴포넌트 */}
            <Header />

            {/** 헤더 높이만큼 Padding-Top (pt-16: 4rem/64px) */}
            <main /*className="pt-16"*/>
              {children}
              <GlobalModal /> {/* 전역 모달 배치 */}
            </main>
            
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );


  // 1. Zustand 스토어에서 필요한 상태 및 액션 가져오기
  ////////////////////////const { user, getProfileApi, isInitialized, isLoading, logout } = useAuthStore();
  //const { user, isInitialized } = useAuthStore();
  /*
    isInitialized: 앱이 처음 켜졌을 때 서버에 물어봤는지 체크
      false면 화면 전체를 로딩으로 막아 보안처리
    isLoading: 로딩바 or 버튼 비활성화 시 유용
  */

  





  

  
  
  




  /* [AS-IS] 
  // 2. 앱 마운트 시 최초 1회 실행: 새로고침 시 토큰 유지 로직
  useEffect(() => {
    console.log("/src/layout.tsx > [새로고침 토큰 유지 로직] > useEffect > getProfileApi() 호출");
    getProfileApi();
  }, [getProfileApi]);

  // 3. 로그아웃 핸들러
  const handleLogout = async () => {
    await logout(); // 서버 쿠키 삭제 및 Zustand 초기화
    alert('로그아웃 되었습니다.');
    router.push('/'); // 메인 페이지로 이동
  };

  */







  /**
   * [중요] 초기화 체크 (isInitialized)
   * 서버로부터 유저 정보를 받아오기 전까지(최초 1회) 로딩 화면 노출
   * 깜빡임(로그인 안 된 것처럼 보이다가 갑자기 로그인 됨)을 방지
   */
  /* AS-IS
  if (!isInitialized) {
    return (
      <html lang="ko">
        <body>
          <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
            <span>로딩중</span>
          </div>
        </body>
      </html>
    );
  }
*/

}



/* 초기값
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
*/